version: 1

formatters:
  standard:
    format: '%(asctime)s %(levelname)s - [%(filename)s: line %(lineno)s] - %(funcName)s - %(message)s'
  error:
    format: "%(levelname)s - %(asctime)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: standard
        filename: /home/izzlee/repos/nem/nem/debugfiles/info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: error
        filename: /home/izzlee/repos/nem/nem/debugfiles/errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: standard
        filename: /home/izzlee/repos/nem/nem/debugfiles/debug.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    critical_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: CRITICAL
        formatter: standard
        filename: /home/izzlee/repos/nem/nem/debugfiles/critical.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    warn_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: WARN
        formatter: standard
        filename: /home/izzlee/repos/nem/nem/debugfiles/warn.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

# loggers:
#   sampleLogger:
#     level: DEBUG
#     handlers: [console]
#     propagate: no
root:
  level: DEBUG
  handlers: [console]
  propogate: yes

# loggers:
#     <module>:
#         level: INFO
#         handlers: [console, info_file_handler, error_file_handler, critical_file_handler, debug_file_handler, warn_file_handler]
#         propogate: no

#     <module.x>:
#         level: DEBUG
#         handlers: [info_file_handler, error_file_handler, critical_file_handler, debug_file_handler, warn_file_handler]
#         propogate: yes